// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQqMP1f2abbe3DUWg1BCZ7piqR0bXmapM',
    appId: '1:1015821425993:web:5c4decb02f4c5c90f54e98',
    messagingSenderId: '1015821425993',
    projectId: 'laptop-savings-tracker',
    authDomain: 'laptop-savings-tracker.firebaseapp.com',
    storageBucket: 'laptop-savings-tracker.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKT3T0Bpuppv-HHGSy84I3cDjv21JjdzA',
    appId: '1:1015821425993:ios:a38e030538de6a04f54e98',
    messagingSenderId: '1015821425993',
    projectId: 'laptop-savings-tracker',
    storageBucket: 'laptop-savings-tracker.firebasestorage.app',
    iosBundleId: 'com.example.savingsTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQqMP1f2abbe3DUWg1BCZ7piqR0bXmapM',
    appId: '1:1015821425993:web:858ced235518520bf54e98',
    messagingSenderId: '1015821425993',
    projectId: 'laptop-savings-tracker',
    authDomain: 'laptop-savings-tracker.firebaseapp.com',
    storageBucket: 'laptop-savings-tracker.firebasestorage.app',
  );
}
